services:
  - type: web
    name: sofabed-chatbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 --threads 2 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT main:app --timeout 120
    envVars:
      - key: GROQ_API_KEY
        value: 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
    plan: free
    # Add memory limit
    resources:
      memory: 512M 