services:
  - type: web
    name: sofabed-chatbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        value: 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 